### PR TITLE
Basic functionality

### PR DESCRIPTION
**Pull request by MarauderXtreme**
I was bored, so I rewrote the whole basic functionality in JS.

### CODE REVIEW

**Comment by lukasmoeller** [comment]
That's very kind of you, however, I am currently in the first semester, a bloody noob and I started this project, to learn HTML etc. So if everything is already done right now it's useless for educational purposes. I mean, if I'd merge everything right now it's not my project anymore, because I've done nothing.

**Comment by lukasmoeller** [comment]
Despite, I really appreciate your help! There is much to learn from your code! :)

**Comment by MarauderXtreme** [comment]
I've talked to @h4llow3En right now.    
I am sorry that I nearly done everything but as I stated I was bored and I wanted to see if I can do this in vanilla JS.    
This is just a basic approach with a little bit of vanilla JS magic. AFAIK you wanted to code this thing in Python so you can maybe deploy this as a basic approach but improve everything with Python Logic, Templates und Theming. (Since this is stil ugly af and not really responsive)

**Comment by lukasmoeller** [comment]
Haha, I know, I am sitting right next to him. You don't have to be sorry :D. I am very thankful! It'll take a while, until I'll have improved everything ... Struggling a little bit with python etc., because I've never done something like this. But you need to crawl before you walk (Denglish FTW!).

And yes, it is ugly indeed :D But before your rework it was even more. But, I've never worked with HTML before and it was (of course) far away from final :)

**Pull request merged**
